const input=document.getElementById('workspaceFile');
const canvas=document.getElementById('workspaceCanvas');
const ctx=canvas.getContext('2d');
const empty=document.getElementById('emptyWorkspace');
let img=null;
let ratio='9 / 16';
let filename='editpro-export.png';
const state={headline:'Breaking News',caption:'Full story in caption',brightness:100,contrast:100,saturation:100,overlay:70,headlineY:6,captionY:92};
const sizes={'1 / 1':[1080,1080],'3 / 4':[1080,1440],'9 / 16':[1080,1920],'16 / 9':[1920,1080]};
const presets={news:['Breaking News','Full story in caption',100,105,105,78,6,92],reel:['Wait For The Twist','Follow for more',105,112,120,62,8,88],product:['New Launch','Limited offer today',108,115,115,50,10,88],clean:['','',100,100,100,0,6,92]};
function setSize(){const s=sizes[ratio]||sizes['9 / 16'];canvas.width=s[0];canvas.height=s[1];}
function readInputs(){state.headline=document.getElementById('headlineInput').value;state.caption=document.getElementById('captionInput').value;state.brightness=+document.getElementById('wsBrightness').value;state.contrast=+document.getElementById('wsContrast').value;state.saturation=+document.getElementById('wsSaturation').value;state.overlay=+document.getElementById('wsOverlay').value;state.headlineY=+document.getElementById('headlineY').value;state.captionY=+document.getElementById('captionY').value;draw();}
function writeInputs(){document.getElementById('headlineInput').value=state.headline;document.getElementById('captionInput').value=state.caption;document.getElementById('wsBrightness').value=state.brightness;document.getElementById('wsContrast').value=state.contrast;document.getElementById('wsSaturation').value=state.saturation;document.getElementById('wsOverlay').value=state.overlay;document.getElementById('headlineY').value=state.headlineY;document.getElementById('captionY').value=state.captionY;}
function fitImage(){const sc=Math.max(canvas.width/img.width,canvas.height/img.height);const w=img.width*sc,h=img.height*sc;ctx.drawImage(img,(canvas.width-w)/2,(canvas.height-h)/2,w,h);}
function textWrap(text,x,y,max,lineH){let line='';String(text).split(' ').forEach((word,i)=>{const test=line+word+' ';if(ctx.measureText(test).width>max&&i>0){ctx.strokeText(line,x,y);ctx.fillText(line,x,y);line=word+' ';y+=lineH}else line=test});ctx.strokeText(line,x,y);ctx.fillText(line,x,y)}
function textBottom(text,x,y,max,lineH){const arr=[];let line='';String(text).split(' ').forEach((word,i)=>{const test=line+word+' ';if(ctx.measureText(test).width>max&&i>0){arr.push(line);line=word+' '}else line=test});arr.push(line);arr.reverse().forEach((l,i)=>{ctx.strokeText(l,x,y-i*lineH);ctx.fillText(l,x,y-i*lineH)})}
function draw(){setSize();ctx.clearRect(0,0,canvas.width,canvas.height);ctx.fillStyle='#111827';ctx.fillRect(0,0,canvas.width,canvas.height);if(!img)return;ctx.filter=`brightness(${state.brightness}%) contrast(${state.contrast}%) saturate(${state.saturation}%)`;fitImage();ctx.filter='none';const a=state.overlay/100,g=ctx.createLinearGradient(0,0,0,canvas.height);g.addColorStop(0,`rgba(0,0,0,${a})`);g.addColorStop(.45,'rgba(0,0,0,0)');g.addColorStop(.7,'rgba(0,0,0,0)');g.addColorStop(1,`rgba(0,0,0,${a})`);ctx.fillStyle=g;ctx.fillRect(0,0,canvas.width,canvas.height);const p=canvas.width*.06;ctx.fillStyle='#fff';ctx.strokeStyle='rgba(0,0,0,.85)';ctx.lineWidth=Math.max(6,canvas.width*.008);ctx.lineJoin='round';ctx.textBaseline='top';ctx.font=`900 ${Math.round(canvas.width*.075)}px Arial`;textWrap(state.headline,p,canvas.height*state.headlineY/100,canvas.width-p*2,canvas.width*.09);ctx.textBaseline='bottom';ctx.font=`800 ${Math.round(canvas.width*.046)}px Arial`;textBottom(state.caption,p,canvas.height*state.captionY/100,canvas.width-p*2,canvas.width*.06)}
input.addEventListener('change',e=>{const f=e.target.files[0];if(!f)return;if(!f.type.startsWith('image/'))return alert('Upload image only in full editor.');filename=f.name.replace(/\.[^/.]+$/,'')+'-edited.png';const r=new FileReader();r.onload=()=>{img=new Image();img.onload=()=>{empty.style.display='none';draw()};img.src=r.result};r.readAsDataURL(f)});
document.querySelectorAll('[data-workspace-ratio]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-workspace-ratio]').forEach(x=>x.classList.remove('active'));b.classList.add('active');ratio=b.dataset.workspaceRatio;draw()});
document.querySelectorAll('[data-template]').forEach(b=>b.onclick=()=>applyPreset(b.dataset.template));
['headlineInput','captionInput','wsBrightness','wsContrast','wsSaturation','wsOverlay','headlineY','captionY'].forEach(id=>document.getElementById(id).addEventListener('input',readInputs));
function applyPreset(n){const p=presets[n];if(!p)return;[state.headline,state.caption,state.brightness,state.contrast,state.saturation,state.overlay,state.headlineY,state.captionY]=p;writeInputs();draw()}
document.getElementById('saveWorkspace').onclick=()=>{localStorage.setItem('editpro-workspace',JSON.stringify({state,ratio}));alert('Project settings saved')};
document.getElementById('loadWorkspace').onclick=()=>{const raw=localStorage.getItem('editpro-workspace');if(!raw)return alert('No saved project');const s=JSON.parse(raw);Object.assign(state,s.state||{});ratio=s.ratio||ratio;writeInputs();draw()};
document.getElementById('exportWorkspace').onclick=()=>{if(!img)return alert('Upload image first');const a=document.createElement('a');a.download=filename;a.href=canvas.toDataURL('image/png');a.click()};
document.querySelectorAll('.tool-tab').forEach(t=>t.onclick=()=>{document.querySelectorAll('.tool-tab').forEach(x=>x.classList.remove('active'));t.classList.add('active')});
setSize();writeInputs();draw();